// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8AacY4HABSaEmYZPI6KdX2PWhXnnbY5A',
    appId: '1:7653412383:web:089094f8ba4039a9124f2a',
    messagingSenderId: '7653412383',
    projectId: 'fir-flutter-app-916b2',
    authDomain: 'fir-flutter-app-916b2.firebaseapp.com',
    storageBucket: 'fir-flutter-app-916b2.appspot.com',
    measurementId: 'G-2WRMVWKV24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkQGzLmtESmwpFqLiAji19k5s7ESeIwQ',
    appId: '1:7653412383:android:01cced434600e733124f2a',
    messagingSenderId: '7653412383',
    projectId: 'fir-flutter-app-916b2',
    storageBucket: 'fir-flutter-app-916b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr3sVrcBs60791mDA8oK109PXuo5QRrjs',
    appId: '1:7653412383:ios:ae980437052e0a74124f2a',
    messagingSenderId: '7653412383',
    projectId: 'fir-flutter-app-916b2',
    storageBucket: 'fir-flutter-app-916b2.appspot.com',
    iosClientId: '7653412383-9njglcmpu9ap9e0plluv1n5qv3e954mo.apps.googleusercontent.com',
    iosBundleId: 'com.abhishekchoksi.firebaseApplication',
  );
}
